# render.yaml - Configuração específica para Render
services:
  - type: web
    name: invictus-poker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    region: ohio
    buildFilter:
      paths:
      - backend/**
      ignoredPaths:
      - frontend/**
    envVars:
    - key: PYTHON_VERSION
      value: 3.11.0
    - key: FLASK_ENV
      value: production
